// <auto-generated />
namespace AirBnB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddHostRoomType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHostRoomType));
        
        string IMigrationMetadata.Id
        {
            get { return "202102111140222_AddHostRoomType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
